baseURL = "https://dataverbinders.github.io/"
languageCode = "nl-nl"
title = "de dataverbinders."

theme = "novela"

paginate = 6

[social]
github= "https://github.com/dataverbinders"
linkedin= "https://www.linkedin.com/company/de-dataverbinders"

[taxonomies]
author = "authors"