baseURL = "http://dedataverbinders.nl/"
languageCode = "nl-nl"
title = "de dataverbinders."

theme = "novela"

paginate = 6

[social]
twitter= "#"
github= "https://github.com/dataverbinders"
linkedin= "https://www.linkedin.com/company/de-dataverbinders"
instagram = "#"
dribbble = "#"
youtube = "#"

[taxonomies]
author = "authors"